CREATE DATABASE IF NOT EXISTS arpesnapdb;

USE arpesnapdb;

CREATE TABLE users (
    sub_id VARCHAR(200) PRIMARY KEY NOT NULL,
    username VARCHAR(100),
    profile_picture VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
